### ISSUE TITLE
Integrate mutation testing

### ISSUE THREAD

**Issue by lukas-lansky** [parthopdas/tddstud10#14]
I use NCrunch daily and I am missing a slightly advanced feature: integrated mutation testing. For example, when a code line doing "b = a * 2" would not break any test when changed into "b = a / 2", instead of green dot a blue dot should be displayed with description of a change that is not covered by the testing suite.

With Roslyn and its support for partial recompilations, there is a chance for this to not be prohibitively slow. I can maybe create a prototype to try this.

**Comment by parthopdas** [comment]
@lukas-lansky, barring bugs with the code coverage module, the current behaviour is to show a grey colour square for code that is not covered. Can you please send across a code (and its test) snippet so I can understand this a bit more? If it is a simple enough fix, we can work on pushing out a hotfix for you.

**Comment by parthopdas** [comment]
@lukas-lansky it will help greatly if you could help me understand this issue with a code snippet or repro step. I am also happy to have you help out with this issue. For now I will close this issue, we can always reopen it later with more details. Thanks for trying out TddStud10, hope you liked it.
