### ISSUE TITLE
Ignore tests in tddStudio environment

### ISSUE THREAD

**Issue by jyotima** [parthopdas/tddstud10#24]

**Comment by jyotima** [comment]
I can think of a few ways to solve this:
1. Implement an attribute similar to [Fact] and ship the dll by nuget. The test methods/classes that are decorated by this attribute will be skipped. Cons: Maintaining another dll and nuget.
2. User can put the list of FQDN of the methods to be skipped in the .user file. Cons: hard to maintain the list in the face of refactorings.
3. Use any generic attribute from C# and skip based on that. Cons: Sounds bad :P
4. put #define in the code and pass the flag at build time. 
5. Implement a attribute that tddstudio will skip and put the FQDN of the attribute in the .user file. Pros: Put only one entry in .user file. Cons: On refactoring this attribute, .user file has to be changes.

I am going to implement #5. Any thoughts?

**Comment by parthopdas** [comment]
I am fine with your choice #5 - assuming you didn't spot any appropriate
attribute predefined in the .NET class library (i.e we've exhausted option
#3, which IMO may not be terrible).
Please also add a test case in one or more of the AcceptanceTest projects.

I think NCrunch does #4.

**Comment by jyotima** [comment]
I havent fully explored the possibilities in existing .net attributes. I see that the Conditional attribute might serve our purpose, but then giving a dev full flexibilty from comfig file to choose his attribute seemed better. Let me explore the full list of .net attributes and see if there is something we can reuse.

**Comment by jyotima** [comment]
While implementing it, there is an issue with using ConditionalAttribute. It wont work in f# with inline functions. It works only on type members. Either we have to fallback to config based attribute or use any other attribute
![image](https://cloud.githubusercontent.com/assets/5457081/17281361/926afece-5750-11e6-95ce-db8f938f7ec4.png)

**Comment by parthopdas** [comment]
Ah yes - coming to think of it ConditionalAttribute would have nuked the member during compilation unless TDDStud10Ignore was #defined - which would have been really bad. Good thing you caught it.

I am starting to prefer the configbased attribute, witch full name of the attribute being in the config file. what do you think?

**Comment by jyotima** [comment]
Actually its not nuking it. I am not sure why. The C# flow works fine and the F# flow as well.
Just that the f# unit tests have to be written inside type. Look at the Log type in the above picture.

Config based approach will work best.

**Comment by parthopdas** [comment]
Fixed with PR #29

**Comment by parthopdas** [comment]
Works beautifully! During the pre-release testing, I was able to make TddStud10 green by ignoring selective tests. And the back to red by removing the setting!!!
