### ISSUE TITLE
The "disable TddStud10" option doesn't seem to be respected across VS restart

### ISSUE THREAD

**Issue by cottsak** [parthopdas/tddstud10#35]
If I disable the tool and then restart VS, I expect the tool to be disabled when VS comes back up. It doesn't seem to respect that. I turn it off then after restart it's on again. Can we fix that?

**Comment by parthopdas** [comment]
Thanks for reporting this issue. This is a duplicate of #1. Do feel free to send a PR.

**Comment by jyotima** [comment]
i am attempting a solution for this. See my PR request.

**Comment by jyotima** [comment]
its merged now. Do try this out.
